import type { Award, Opportunity, Program } from "@ogg/schema";

/** Curated starter set — wave-1 ecosystems for technical grants. */
export const seedPrograms: Program[] = [
  {
    id: "ef-esp",
    ecosystem: "ethereum",
    name: "Ethereum Foundation — Ecosystem Support Program",
    instrument: "milestone_grant",
    focusCategories: [
      "protocol_clients",
      "zk_cryptography",
      "security",
      "developer_tooling",
      "analytics_transparency",
      "privacy",
    ],
    typicalCheckUsd: { min: 10000, max: 500000, medianHint: 75000 },
    url: "https://esp.ethereum.foundation/",
    status: "rolling",
    notes:
      "Quarterly allocations often $7M–$14M total. Large checks for clients/ZK/security/research-grade data.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "optimism-retro-devtools",
    ecosystem: "optimism",
    name: "Optimism Retro Funding — Dev Tooling",
    instrument: "retro_funding",
    focusCategories: ["developer_tooling"],
    typicalCheckUsd: { min: 10000, max: 200000, medianHint: 25000 },
    url: "https://optimism.io/blog/retro-funding-2025",
    status: "rolling",
    notes:
      "Season 7: median ~24.7K OP, max ~356K OP across OSS toolchain with real dependents.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "solana-foundation-public-goods",
    ecosystem: "solana",
    name: "Solana Foundation — Public Goods / Open Source",
    instrument: "milestone_grant",
    focusCategories: ["developer_tooling", "infrastructure_rpc", "education_community"],
    typicalCheckUsd: { min: 10000, max: 100000, medianHint: 40000 },
    url: "https://solana.org/grants",
    status: "rolling",
    notes: "Public-goods average check historically cited around ~$40k.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "arbitrum-foundation-grants",
    ecosystem: "arbitrum",
    name: "Arbitrum Foundation Grant Program",
    instrument: "milestone_grant",
    focusCategories: ["developer_tooling", "defi_primitive", "infrastructure_rpc"],
    typicalCheckUsd: { min: 20000, max: 150000, medianHint: 60000 },
    url: "https://arbitrum.foundation/grants",
    status: "rolling",
    notes: "Typical builder grants ~$20k–$150k in ARB; separate from mega incentive programs.",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "avalanche-retro9000",
    ecosystem: "avalanche",
    name: "Avalanche Retro9000",
    instrument: "retro_funding",
    focusCategories: ["infrastructure_rpc", "developer_tooling", "defi_primitive"],
    typicalCheckUsd: { min: 500, max: 200000, medianHint: 30000 },
    url: "https://www.avax.network/about/blog/retro9000-everything-you-need-to-know",
    status: "rolling",
    notes: "Up to $40M pool; usage/burn based rounds; lifetime caps may apply.",
    updatedAt: new Date().toISOString(),
  },
];

export const seedAwards: Award[] = [
  {
    id: "award-op-devtools-median-ref",
    programId: "optimism-retro-devtools",
    ecosystem: "optimism",
    projectName: "Season 7 Dev Tooling median reference",
    focusCategories: ["developer_tooling"],
    amount: {
      nativeAmount: 24700,
      nativeAsset: "OP",
      usdEstimate: null,
      pricedAt: null,
      confidence: "medium",
    },
    awardedAt: "2025-07-01T00:00:00.000Z",
    sourceUrl:
      "https://gov.optimism.io/t/season-7-retro-funding-early-evidence-on-developer-tooling-impact/10162",
    evidence: "Reported median reward ~24.7K OP across 97 projects",
  },
  {
    id: "award-solana-avg-public-goods-ref",
    programId: "solana-foundation-public-goods",
    ecosystem: "solana",
    projectName: "Solana public-goods average check reference",
    focusCategories: ["developer_tooling"],
    amount: {
      nativeAmount: null,
      nativeAsset: "USDC",
      usdEstimate: 40000,
      pricedAt: "2026-01-01T00:00:00.000Z",
      confidence: "medium",
    },
    awardedAt: "2026-01-01T00:00:00.000Z",
    sourceUrl: null,
    evidence: "Foundation-cited average ~$40k for public-good/open-source grants",
  },
];

export const seedOpportunities: Opportunity[] = [
  {
    id: "opp-ef-esp-rolling",
    programId: "ef-esp",
    ecosystem: "ethereum",
    title: "ESP rolling applications — data infra / developer tooling",
    instrument: "milestone_grant",
    deadlineAt: null,
    url: "https://esp.ethereum.foundation/",
    requirements: [
      "Clear public-goods impact on Ethereum",
      "Open methodology / reproducible outputs preferred",
      "Milestone plan",
    ],
    focusCategories: ["indexing_data", "analytics_transparency", "developer_tooling"],
    estimatedCheckUsd: {
      nativeAmount: null,
      nativeAsset: "USD",
      usdEstimate: 75000,
      pricedAt: new Date().toISOString(),
      confidence: "low",
    },
    discoveredAt: new Date().toISOString(),
  },
  {
    id: "opp-op-retro-devtools",
    programId: "optimism-retro-devtools",
    ecosystem: "optimism",
    title: "Retro Funding Dev Tooling — ship OSS with dependents",
    instrument: "retro_funding",
    deadlineAt: null,
    url: "https://optimism.io/blog/retro-funding-2025",
    requirements: [
      "Open-source GitHub history",
      "Published package (npm/crates) where applicable",
      "Measurable usage by Superchain builders",
    ],
    focusCategories: ["developer_tooling"],
    estimatedCheckUsd: {
      nativeAmount: 24700,
      nativeAsset: "OP",
      usdEstimate: null,
      pricedAt: null,
      confidence: "medium",
    },
    discoveredAt: new Date().toISOString(),
  },
];
